Halt on errors in build_lib.sh for Catapult, Symbolic and Vivado Accelerator.
"set -e" has been already added for other backends.
It allows to print compilations errors, e.g.:
firmware/myproject.h:5:10: fatal error: ac_fixed.h: No such file or directory
    5 | #include <ac_fixed.h>

instead of ignoring them and crashing later, e.g.:
firmware/myproject-0b348075.so: cannot open shared object file: No such file or directory